name: Development Env

on:
  push:
    branches: 
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up JDK 1.17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn clean install

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build
      if: success()
      run: |
        docker build . -t imeshdocker/springboot-new-app:${SHORT_SHA}
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "docker.io/imeshdocker/springboot-new-app:${{ env.SHORT_SHA }}"
        format: 'table'
        exit-code: "1"
        ignore-unfixed: true
        vuln-type: 'library'
        # output: 'report.txt'
        # severity: 'CRITICAL,HIGH,MEDIUM'

    - name: Upload Dev Report Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Vulnerability Report
        path: ./report.txt
        retention-days: '7'

    # - name: Run Trivy vulnerability scanner 2
    #   uses: aquasecurity/trivy-action@master
    #   with:
    #     image-ref: "docker.io/imeshdocker/springboot-new-app:${{ env.SHORT_SHA }}"
    #     format: 'sarif'
    #     output: 'trivy-results.sarif'

    # - name: Print SARIF File Contents
    #   run: cat trivy-results.sarif

    # - name: Upload Trivy scan results to GitHub Security tab
    #   uses: github/codeql-action/upload-sarif@v2
    #   with:
    #     sarif_file: 'trivy-results.sarif'

    - name: Docker Push
      if: success()
      run: |
        docker push imeshdocker/springboot-new-app:${SHORT_SHA}