name: Development Env

on:
  push:
    branches: 
      - development

jobs:
  build:
    runs-on: dev-runner

    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up JDK 1.17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn clean install

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Build
      if: success()
      run: |
        docker build . -t imeshdocker/springboot-new-app:${SHORT_SHA}
        docker push imeshdocker/springboot-new-app:${SHORT_SHA}
